server:
  8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studyshare
    driver-class-name: org.postgresql.Driver
    username: work1
    password: work1

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.dataset.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        dataset:
          mapper: debug
          service: info
          controller: info

dataset:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 72000000
    user-token-name: authentication
  wechat:
    appid: wx7a3595bf0591a098
    secret: 7fe6ca5008c76a72be89f4d23c271e17
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t62r16mCDUGb6L6z6UE
    access-key-secret: r2yfN05jptW4eH7rxGNVnZGxHAmccz
    bucket-name: maybetestbucket

